const products = [
  {
    _id: "33332",
    name: "Miękki sweter z wełny alpaki",
    image: "/images/golf.jpg",
    description: "Miękki golf. Skład: 100% wełna alpaki.",
    category: "Sweaters",
    price: 89.99,
    countInStock: 10,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "367632",
    name: "Sukienka kopertowa",
    image: "/images/kopertowa-sukienka.webp",
    description: "Dzianinowa sukienka za kolano.",
    category: "Dresses",
    price: 189.99,
    countInStock: 0,
    rating: 5.0,
    numReviews: 16,
  },
  {
    _id: "898332",
    name: "Sukienka maxi",
    image: "/images/sukienka.jpg",
    description: "Wzorzysta sukienka z oryginalnym printem.",
    category: "Dresses",
    price: 389.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 16,
  },
  {
    _id: "94452",
    name: "Garnitur w kratę",
    image: "/images/garnitur-w-krate.webp",
    description:
      "Marynarka garniturowa wykonana z tkaniny w kratę. -kołnierz z klapami -długie rękawy-dwurzędowe zapięcie na guziki -dwie kieszenie listewkowe -wewnątrz gładka podszewka",
    category: "suits",
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "1898332",
    name: "Cardigan",
    image: "/images/cardigan.webp",
    description:
      "Krótki kardigan o swobodnym kroju. 100% wełna merynosa. -długie rękawy z obniżoną linią ramion -zapięcie na guziki -brzegi wykończone ściagaczem",
    category: "Sweaters",
    price: 129.99,
    countInStock: 5,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "56533",
    name: "Liliowa czapka",
    image: "/images/liliowa-czapka.webp",
    description: "Wełniana czapka beanie. Skład: 70% wełna merino, 30% bawełna",
    category: "Winter hats",
    price: 99.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },

  {
    _id: "2133002",
    name: "Beżowa czapka",
    image: "/images/bezowa-czapka.jpg",
    description: "Wełniana czapka beanie. Skład: 100% wełna merino",
    category: "Winter hats",
    price: 159.99,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "454552",
    name: "Łososiowa czapka",
    image: "/images/lososiowa-czapka.webp",
    description: "Wełniana czapka beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 159.99,
    countInStock: 0,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: "3555122",
    name: "Pomarańczowa czapka",
    image: "/images/pomaranczowa-czapka.jpg",
    description: "Wełniana czapka beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 159.99,
    countInStock: 10,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: "9933232",
    name: "Żółta czapka",
    image: "/images/zolta-czapka.webp",
    description: "Wełniana czapka beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 159.99,
    countInStock: 5,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: "726588",
    name: "Zielona czapka",
    image: "/images/zielona-czapka.webp",
    description: "Wełniana czapka dziecięca, beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 129.99,
    countInStock: 6,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: "673222",
    name: "Różowa czapka",
    image: "/images/rozowa-czapka.webp",
    description: "Wełniana czapka dziecięca, beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 129.99,
    countInStock: 10,
    rating: 5.0,
    numReviews: 10,
  },
  {
    _id: "339021",
    name: "Niebieska czapka",
    image: "/images/niebieska-czapka.webp",
    description: "Wełniana czapka beanie. Skład: 100% wełna alpaki",
    category: "Winter hats",
    price: 159.99,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
